# ModpackAI 플러그인 설정

# AI 서버 설정
ai:
  server_url: "http://localhost:5000"
  modpack_name: "unknown"
  modpack_version: "1.0"

# AI 어시스턴트 아이템 설정
ai_item:
  material: "BOOK"
  name: "§6§l모드팩 AI 어시스턴트"
  lore:
    - "§7우클릭하여 AI와 대화하세요"
    - "§7모드팩 관련 질문에 답변해드립니다"
    - ""
    - "§e§l사용법:"
    - "§f- 우클릭: AI 채팅창 열기"
    - "§f- 제작법 질문 시 자동으로 표시"

# GUI 설정
gui:
  chat_title: "§6§l모드팩 AI 어시스턴트"
  chat_size: 54
  recipe_title: "§6§l제작법"
  recipe_size: 27

# 메시지 설정
messages:
  no_permission: "§c이 기능을 사용할 권한이 없습니다."
  ai_error: "§cAI 서버와 통신 중 오류가 발생했습니다."
  recipe_not_found: "§c제작법을 찾을 수 없습니다."
  item_given: "§aAI 어시스턴트 아이템을 받았습니다!"
  modpack_switch_success: "§a모드팩이 성공적으로 변경되었습니다."
  modpack_switch_error: "§c모드팩 변경 중 오류가 발생했습니다."

# 권한 설정
permissions:
  require_permission: false
  node: "modpackai.use"
  admin_node: "modpackai.admin"

# 디버그 설정
debug:
  enabled: false 