name: ModpackAI
version: 1.0.0
main: com.modpackai.ModpackAIPlugin
api-version: 1.13
authors: [ModpackAI Team]
description: 마인크래프트 모드팩 전문 AI 어시스턴트

commands:
  modpackai:
    description: 모드팩 AI 어시스턴트 명령어
    usage: /modpackai <chat|recipe|models|current|switch|help>
    permission: modpackai.use

permissions:
  modpackai.use:
    description: 기본 AI 어시스턴트 사용 권한
    default: true
  modpackai.admin:
    description: 관리자 권한 (모드팩 변경 등)
    default: op 